In [15]:
import numpy as np
import plotly.express as px
import pandas as pd
from datetime import datetime
import re
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
import time
import streamlit as st
from pymongo import MongoClient
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

In [17]:
MONGO_URI = "mongodb+srv://int_dados:e7bUe2bXbKDu3Xzr@rumo-dev2.hbdcrld.mongodb.net/?authSource=admin"
DB_NAME = "supervisorio"

In [ ]:
import asyncio
from concurrent.futures import ThreadPoolExecutor
import pandas as pd
import os


def salvar_parquet(df, path):
    # garante que a pasta existe
    os.makedirs(os.path.dirname(path), exist_ok=True)
    df.to_parquet(path, index=False, engine="pyarrow")


async def salvar_tudo_assincrono(dfs, paths):
    loop = asyncio.get_event_loop()

    with ThreadPoolExecutor() as executor:
        tarefas = [
            loop.run_in_executor(executor, salvar_parquet, df, path)
            for df, path in zip(dfs, paths)
        ]

        await asyncio.gather(*tarefas)

In [18]:
def busca_TBOGI(vagao):
    # Conexão com o MongoDB
    vagao = int(vagao)
    client = MongoClient(
        MONGO_URI)

    # Definição do filtro
    filter = {'car_num': re.compile(f"{vagao}")}

    # Consulta
    cursor = client[DB_NAME]['tbogi_treated'].find(
        filter)

    # Converter o cursor em lista e depois em DataFrame
    df = pd.DataFrame(list(cursor))

    # (Opcional) Remover a coluna _id, se não for necessária
    if '_id' in df.columns:
        df.drop('_id', axis=1, inplace=True)

    return df

df_tbogi = busca_TBOGI(8413916)

c:\Users\leona\anaconda3\Lib\site-packages\pymongo\pyopenssl_context.py:352: CryptographyDeprecationWarning: Parsed a negative serial number, which is disallowed by RFC 5280. Loading this certificate will cause an exception in the next release of cryptography.
  _crypto.X509.from_cryptography(x509.load_der_x509_certificate(cert))

In [20]:
df_tbogi["valor_mod_pd"] = df_tbogi["tp"].abs()
df_tbogi

,veiculo,thingName,originDeviceThingName,timestamp,car_seq_num,car_init,car_num,equipment_type,equipment_orientation,car_truck_count,...,rot,te,shift,num_in_car,num_in_train,axle_speed,axle_spacing,aoa,tp,valor_mod_pd
0,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-07 15:17:32.944,58,HFT,8413916,F,B,2,...,0.0,-2.8,0.000,3,235,22.9,12159,0.3,-1.756,1.756
1,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-07 15:17:32.944,58,HFT,8413916,F,B,2,...,0.0,3.5,0.000,2,234,23.1,1794,0.0,-1.956,1.956
2,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-07 15:17:32.944,58,HFT,8413916,F,B,2,...,0.0,3.5,0.000,1,233,23.1,2412,-0.1,1.544,1.544
3,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-07 15:17:32.944,58,HFT,8413916,F,B,2,...,0.0,-2.8,0.000,4,236,23.0,1799,-0.1,1.044,1.044
4,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-11 16:30:05.663,4,HFT,8413916,F,A,2,...,0.0,-0.7,4.055,2,19,20.8,12162,0.1,3.705,3.705
5,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-11 16:30:05.663,4,HFT,8413916,F,A,2,...,0.0,2.5,1.555,4,17,20.8,2327,-0.1,2.805,2.805
6,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-11 16:30:05.663,4,HFT,8413916,F,A,2,...,0.0,-0.7,4.055,1,20,20.9,1776,0.2,4.405,4.405
7,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-11 16:30:05.663,4,HFT,8413916,F,A,2,...,0.0,2.5,1.555,3,18,20.9,1781,0.0,0.305,0.305
8,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-15 17:43:15.241,41,HFT,8413916,F,B,2,...,0.0,3.8,0.000,2,166,22.9,1795,0.2,-1.660,1.660
9,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-15 17:43:15.241,41,HFT,8413916,F,B,2,...,0.0,-3.2,0.000,3,167,22.9,12219,0.1,-1.960,1.960
10,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-15 17:43:15.241,41,HFT,8413916,F,B,2,...,0.0,-3.2,0.000,4,168,23.0,1795,-0.1,1.240,1.240
11,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-15 17:43:15.241,41,HFT,8413916,F,B,2,...,0.0,3.8,0.000,1,165,22.9,2485,0.0,2.140,2.140
12,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-19 00:39:31.223,44,HFT,8413916,F,A,2,...,0.0,1.8,0.937,3,178,37.3,1771,-0.2,0.037,0.037
13,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-19 00:39:31.223,44,HFT,8413916,F,A,2,...,0.0,1.8,0.937,4,177,37.2,2336,-0.1,1.837,1.837
14,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-19 00:39:31.223,44,HFT,8413916,F,A,2,...,0.0,-1.4,3.537,1,180,37.8,1774,0.1,4.237,4.237
15,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-19 00:39:31.223,44,HFT,8413916,F,A,2,...,0.0,-1.4,3.537,2,179,37.6,12200,0.0,2.837,2.837
16,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-21 17:40:50.472,39,HFT,8413916,F,B,2,...,0.0,-2.1,0.000,3,159,40.6,12225,0.3,-1.574,1.574
17,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-21 17:40:50.472,39,HFT,8413916,F,B,2,...,0.0,3.9,0.000,1,157,40.5,2489,0.0,2.026,2.026
18,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-21 17:40:50.472,39,HFT,8413916,F,B,2,...,0.0,-2.1,0.000,4,160,40.6,1795,0.0,0.526,0.526
19,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-21 17:40:50.472,39,HFT,8413916,F,B,2,...,0.0,3.9,0.000,2,158,40.6,1792,-0.1,-1.874,1.874
20,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-26 17:31:51.606,64,HFT,8413916,F,A,2,...,0.0,-0.4,4.706,1,260,46.2,1770,-0.1,4.906,4.906
21,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-26 17:31:51.606,64,HFT,8413916,F,A,2,...,0.0,-0.4,4.706,2,259,46.0,12180,0.1,4.506,4.506
22,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-26 17:31:51.606,64,HFT,8413916,F,A,2,...,0.0,3.7,2.256,3,258,45.7,1778,0.0,0.406,0.406
23,HFT-8413916,HFT-8413916,Rumo_Americana,2025-10-26 17:31:51.606,64,HFT,8413916,F,A,2,...,0.0,3.7,2.256,4,257,45.6,2485,0.4,4.106,4.106
24,HFT-8413916,HFT-8413916,Rumo_Americana,2025-11-14 20:28:09.659,44,HFT,8413916,F,B,2,...,0.0,2.9,0.000,1,177,41.0,2495,0.2,1.261,1.261
25,HFT-8413916,HFT-8413916,Rumo_Americana,2025-11-14 20:28:09.659,44,HFT,8413916,F,B,2,...,0.0,-1.0,0.000,4,180,41.1,1794,0.0,0.461,0.461
26,HFT-8413916,HFT-8413916,Rumo_Americana,2025-11-14 20:28:09.659,44,HFT,8413916,F,B,2,...,0.0,-1.0,0.000,3,179,41.1,12228,0.3,-0.539,0.539
27,HFT-8413916,HFT-8413916,Rumo_Americana,2025-11-14 20:28:09.659,44,HFT,8413916,F,B,2,...,0.0,2.9,0.000,2,178,41.1,1794,0.0,-1.639,1.639
28,HFT-8413916,HFT-8413916,Rumo_Americana,2025-11-19 01:39:21.158,45,HFT,8413916,F,A,2,...,0.0,2.4,0.000,4,181,50.3,2360,0.1,2.261,2.261
29,HFT-8413916,HFT-8413916,Rumo_Americana,2025-11-19 01:39:21.158,45,HFT,8413916,F,A,2,...,0.0,-1.7,4.111,2,183,50.5,12168,0.4,3.261,3.261
30,HFT-8413916,HFT-8413916,Rumo_Americana,2025-11-19 01:39:21.158,45,HFT,8413916,F,A,2,...,0.0,2.4,0.000,3,182,50.3,1775,-0.5,-0.139,0.139
31,HFT-8413916,HFT-8413916,Rumo_Americana,2025-11-19 01:39:21.158,45,HFT,8413916,F,A,2,...,0.0,-1.7,4.111,1,184,50.7,1775,0.1,4.961,4.961

In [24]:
df_resumo = (
    df_tbogi.groupby("timestamp_received", as_index=False)["valor_mod_pd"]
    .max()
    .rename(columns={"valor_mod_pd": "max_valor_mod_pd"})
    .sort_values(by="timestamp_received")
)
df_resumo

       timestamp_received  max_valor_mod_pd
0 2025-10-07 15:17:28.177             1.956
1 2025-10-11 16:30:01.275             4.405
2 2025-10-15 17:43:13.994             2.140
3 2025-10-19 00:39:27.951             4.237
4 2025-10-21 17:40:45.525             2.026
5 2025-10-26 17:31:46.666             4.906
6 2025-11-14 20:28:05.023             1.639
7 2025-11-19 01:39:17.980             4.961

In [ ]:
def inserir_TBOGI_hist(df_TBOGI_trated):
    df_TBOGI_trated_histgeral = df_TBOGI_trated.copy()
    print(df_TBOGI_trated)
    # 1) Garantir datetime (com hora) na coluna timestamp_received
    df_TBOGI_trated_histgeral['INICIO'] = pd.to_datetime(
        df_TBOGI_trated_histgeral['timestamp_received'])
    df_TBOGI_trated_histgeral['Tipo_Evento'] = "Passagem TBOGI"
    # + \            df_TBOGI_trated_histgeral['timestamp_received'].astype(str)
    df_TBOGI_trated_histgeral['Evento'] = "TBOGI"

    df_TBOGI_trated_histgeral['Texto_Completo'] = "max_valor_mod_pd = " + \
        df_TBOGI_trated_histgeral['max_valor_mod_pd'].astype(str)

    df_TBOGI_trated_histgeral["timestamp_received"] = pd.to_datetime(
        df_TBOGI_trated_histgeral["timestamp_received"], format="%Y-%m-%d %H:%M")
    df_TBOGI_trated_histgeral["FIM"] = (
        df_TBOGI_trated_histgeral["timestamp_received"] + pd.to_timedelta(12, unit="h")
    )
    df_TBOGI_trated_histgeral['Tipo_Evento'] = "TBOGI"

    df_TBOGI_total = df_TBOGI_trated_histgeral[[
        'Evento', 'INICIO', 'FIM', 'Texto_Completo', 'Tipo_Evento']]

    return df_TBOGI_total

In [4]:
df_164   = pd.read_parquet("temp/df_164.parquet")
df_trkv  = pd.read_parquet("temp/df_trkv.parquet")
df_WCM   = pd.read_parquet("temp/df_WCM.parquet")
df_z369  = pd.read_parquet("temp/df_z369.parquet")
df_z851  = pd.read_parquet("temp/df_z851.parquet")
df_z1568 = pd.read_parquet("temp/df_z1568.parquet")

In [5]:
df_z369

,NOTA,ATIVO,Flag,MODELO,STATUS,TEXTO,TEXTO AVARIA,TEXTO CAUSA,TP ATIVO,TP NOTA,data_sincronizacao,dt_abertura_trated,dt_fechamento_trated,dt_last_udate_trated,ATIVO_tratado
0,24165721,304298HPT,,GRANELEIROS,MSPN,TR|PRATO PIÃO|ANEL|DISCO BORDEADO QUEBR|,*AMORT:PRATO PIÃO*,|CA||||ANEL DO DISCO BORDEADO QUEBRADO C,VAGÃO,M1,2025-11-14 16:10:52.947,2025-10-31,None,2025-10-31,304298
1,24207666,8400032HPT,,GRANELEIROS,MSPN,CCT|ENGATE|MANDÍBULA|QUEBRADA,KM 0232+700 TREM I48 *RAF 10836*,P.A 1H,VAGÃO,M2,2025-11-15 15:50:53.762,2025-11-04,None,2025-11-14,8400032
2,24038745,659428HTT,,GRANELEIROS,MSPN,VAGÃO EM GARANTIA GBMX ATÉ 5/2028,VAGÃO EM GARANTIA GBMX ATÉ 5/2028,None,VAGÃO,M4,2025-11-14 16:10:52.947,2025-05-27,None,2025-05-27,659428
3,23806541,8442568HPT,,GRANELEIROS,MSPN,FR|VALV VAZIO CARREG|MANGUEIRA|FURADA|,*Freio:Vazio Carregado*,|CA||||Pequeno vazamento VALV VAZIO CAR,VAGÃO,M1,2025-11-14 16:10:52.947,2025-04-07,None,2025-04-07,8442568
4,23655705,579505PCT,,PLATAFORMAS,MSPN,Análise Acionamento - Inspeção de DDV,Análise Acionamento - Inspeção de DDV,Análise Acionamento - Inspeção de DDV,VAGÃO,M8,2025-11-14 16:10:52.947,2024-01-08,None,2024-01-08,579505
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20708,24239202,549797HFT,,GRANELEIROS,MSPN,CCT|ENGATE|SUPORTE ENGATE|QUEBRADO|,*CCT:SUPORTE DO ENGATE*,None,VAGÃO,M1,2025-11-27 15:53:57.430,2025-11-27,None,NaT,549797
20709,24238767,306355HPT,,GRANELEIROS,MSPN,FR|FREIO|CW|RODA FRIA,*Roda Fria:*,FR|FREIO|CW|RODA FRIA,VAGÃO,M1,2025-11-27 15:53:57.430,2025-11-26,None,NaT,306355
20710,24239174,303500HPT,,GRANELEIROS,MSPN,TR|PACOTE DE MOLA|MOLA|QBD 1 MOLA | 1,*AMORT:MOLA*,None,VAGÃO,M1,2025-11-27 15:53:57.430,2025-11-27,None,NaT,303500
20711,24238466,548588HFT,,GRANELEIROS,MSPN,CCT|ENGATE|ENGATE|CHAPA DESGASTE FALT|,*CCT:CHAPA DO ENGATE*,|CB||||ENGATE ENGATE CHAPA DESGASTE FALT,VAGÃO,M1,2025-11-27 15:53:57.430,2025-11-26,None,NaT,548588
20712,24239065,3504280HTT,,GRANELEIROS,MSPN,RD|RODA|FRISO|DIFERENÇA|,*Rd:Friso*,|||4E 4D||4E 32cm e 4D 20cm RODA FRISO D,VAGÃO,M1,2025-11-27 15:53:57.430,2025-11-26,None,NaT,3504280

In [13]:
contagem_pivot = (
    df_z369[df_z369["STATUS"] == "MSPN"]
    .pivot_table(
        index="ATIVO",
        columns="TP NOTA",
        values="STATUS",
        aggfunc="count",
        fill_value=0
    )
)

contagem_pivot

TP NOTA     M1  M2  M3  M4  M6  M7  M8  M9
ATIVO
1002180HNS   0   0   0   0   1   0   0   0
1002244HNS   2   0   0   0   0   0   0   0
1002538HNS   0   0   0   0   1   0   0   0
160342HAS    1   0   0   0   0   0   0   0
160369HAS    1   0   0   0   0   0   0   0
...         ..  ..  ..  ..  ..  ..  ..  ..
994898TCS    1   0   0   0   0   0   0   0
994901TCS    1   0   0   0   0   0   0   0
994910TCS    0   0   0   0   0   0   1   0
994936TCS    0   0   0   0   0   0   1   0
994944TCS    0   0   0   0   0   0   1   0

[9144 rows x 8 columns]

In [ ]:
# Conversões sem alterar as colunas originais
dt_164     = pd.to_datetime(df_164['DT_CARGA'], errors='coerce')
dt_trkv    = pd.to_datetime(df_trkv['data_sincronizacao'], errors='coerce')
dt_WCM     = pd.to_datetime(df_WCM['json_trem_TrainTime'], errors='coerce')
dt_z369    = pd.to_datetime(df_z369['dt_last_udate_trated'], errors='coerce')
dt_z851    = pd.to_datetime(df_z851['Atualizacao'], errors='coerce')
dt_z1568   = pd.to_datetime(df_z1568['dt_fim_trated'], errors='coerce')

# Datas mais recentes
data_mais_recente_164   = dt_164.max()
data_mais_recente_trkv  = dt_trkv.max()
data_mais_recente_WCM   = dt_WCM.max()
data_mais_recente_z369  = dt_z369.max()
data_mais_recente_z851  = dt_z851.max()
data_mais_recente_z1568 = dt_z1568.max()

print("164:", data_mais_recente_164)
print("TRKV:", data_mais_recente_trkv)
print("WCM:", data_mais_recente_WCM)
print("Z369:", data_mais_recente_z369)
print("Z851:", data_mais_recente_z851)
print("Z1568:", data_mais_recente_z1568)

In [3]:
def tratar_WCM(df_WCM):

    # Garantir datetime
    df_WCM['json_trem_TrainTime'] = pd.to_datetime(
        df_WCM['json_trem_TrainTime'], errors='coerce'
    )

    # Criar coluna somente com a data
    df_WCM['Data'] = df_WCM['json_trem_TrainTime'].dt.date

    # Agrupamento por veículo + data
    df_WCM_max = (
        df_WCM.groupby(
            ['json_Identificação do veículo', 'Data'],
            as_index=False
        )['json_Força de pico de impacto da roda (kN)']
        .max()
        .rename(columns={
            'json_Força de pico de impacto da roda (kN)': 'Maior_Impacto_kN'
        })
        .sort_values(by=['json_Identificação do veículo', 'Data'])
    )
    df_WCM_max['key'] = df_WCM_max['json_Identificação do veículo'].str.split(
    ).str[-1].astype(int)

    return df_WCM_max

In [ ]:


df_trkv["max_valor"] = df_trkv[["A#L_1", "A#L_2", "A#R_1",
                                "A#R_2", "B#L_1", "B#L_2", "B#R_1", "B#R_2"]].max(axis=1)
df_trkv_filtred = df_trkv[["CarIDInitial",
                            "CarIDNumber", "timestr", "max_valor"]]

df_trkv_filtred = df_trkv_filtred[df_trkv_filtred["CarIDInitial"].notna()]
df_trkv_filtred = df_trkv_filtred[df_trkv_filtred["max_valor"].notna()]
df_trkv_filtred['timestr'] = pd.to_datetime(
    df_trkv_filtred['timestr'], format="%d/%m/%Y %H:%M:%S", errors='coerce')
df_trkv_filtred['key'] = df_trkv_filtred['CarIDNumber'].astype(int)

df_z851['key'] = df_z851['EQUNR'].str.replace(
    r'[^0-9]', '', regex=True).astype(int)
df1 = df_z851
df2 = df_trkv_filtred

# 1. Filtra apenas passagens com medição não nula
df2_filtrado = df2[df2['max_valor'].notnull()].copy()

# 2. Ordena por equipamento e data (da mais recente para a mais antiga)
df2_filtrado = df2_filtrado.sort_values(
    ['key', 'timestr'], ascending=[True, True])

# ============================================================
# A) PEGAR A ÚLTIMA MEDIÇÃO E A DATA DA ÚLTIMA MEDIÇÃO
# ============================================================

# Ordena por data DESC dentro da chave
df2_desc = df2_filtrado.sort_values(
    ['key', 'timestr'], ascending=[True, False])

# Pega a última linha por equipamento
df_last = df2_desc.groupby('key').first().reset_index()

df_last.rename(columns={
    'max_valor': 'ultima_medicao',
    'timestr': 'data_ultima_medicao'
}, inplace=True)

# ============================================================
# B) PEGAR A MAIOR MEDIÇÃO ENTRE AS 3 ÚLTIMAS PASSAGENS
# ============================================================

# Pega rank das 3 últimas (já está ordenado ascendente)
df2_filtrado['rank'] = df2_filtrado.groupby(
    'key')['timestr'].rank(method='first', ascending=False)

df_top3 = df2_filtrado[df2_filtrado['rank'] <= 3]

df_max = df_top3.groupby('key')['max_valor'].max().reset_index()
df_max.rename(columns={'max_valor': 'max_medicao_ultimas_3'}, inplace=True)

# ============================================================
# C) MERGE FINAL
# ============================================================

df_final = df1.merge(df_max, on='key', how='left') \
    .merge(df_last[['key', 'ultima_medicao', 'data_ultima_medicao']],
            on='key', how='left')

# df_final = df_final[["EQUNR", "MODELO", "STATUS", "DATA_DE_FABRICACAO_trated", "DATA_GARANTIA_trated", "ULTIMA_RG",
#                      "KM_RODADO_DESDE_ULTIMA_RG", "max_medicao_ultimas_3", "ultima_medicao", "data_ultima_medicao", "key"]]

df_tratado = df_final.rename(columns={
    'max_medicao_ultimas_3': 'TRKV_max_medicao_ultimas_3',
    'ultima_medicao': 'TRKV_ultima_medicao',
    'data_ultima_medicao': 'TRKV_last_timestamp'
})

In [ ]:
8413916HFT

In [ ]:
df_filtrado = df_trkv_filtred[df_trkv_filtred["key"] == 8413916]
df_filtrado

In [ ]:
df_filtrado2 = df_trkv[df_trkv["CarIDNumber"] == 8413916]
df_filtrado2

In [ ]:
df_trkv

In [ ]:
  # Garantir ordenação correta

def Trataroutliers_trkv(df_filtrado):
  df = df_filtrado.sort_values(["key", "timestr"])

  # Cálculo de min_3 e max_3 por key
  df["min_3"] = (
      df.groupby("key")["max_valor"]
        .rolling(window=3)
        .min()
        .shift(1)
        .reset_index(level=0, drop=True)
  )

  df["max_3"] = (
      df.groupby("key")["max_valor"]
        .rolling(window=3)
        .max()
        .shift(1)
        .reset_index(level=0, drop=True)
  )

  # Regras com tolerância de ±30%
  df["DESCARTAR"] = (
      (df["max_valor"] > df["max_3"] * 1.3) |   # 30% acima
      (df["max_valor"] < df["min_3"] * 0.7)     # 30% abaixo
  )

  # Coluna textual opcional
  df["STATUS"] = df["DESCARTAR"].map({True: "DESCARTAR", False: "OK"})
  df
  return df

In [ ]:
df_trkv = df_trkv[df_trkv["CarIDNumber"]== 559652]
df_trkv

In [ ]:
def tratar_trkv(df_trkv):

    # Usar data_sincronizacao pois timestr está vazio
    df_trkv['timestr'] = pd.to_datetime(
        df_trkv['data_sincronizacao'], errors='coerce'
    )

    df_trkv['Data'] = df_trkv['timestr'].dt.date

    colunas_impacto = [
        'A#L_1', 'A#L_2', 'A#R_1', 'A#R_2',
        'B#L_1', 'B#L_2', 'B#R_1', 'B#R_2'
    ]

    df_trkv[colunas_impacto] = df_trkv[colunas_impacto].replace(0, np.nan)

    df_trkv['Maior_Impacto_Linha'] = df_trkv[colunas_impacto].max(axis=1)

    df_trkv_max = (
        df_trkv.groupby('Data', as_index=False)['Maior_Impacto_Linha']
        .max()
        .rename(columns={'Maior_Impacto_Linha': 'Maior_Impacto_Diario'})
    )

    return df_trkv_max

In [ ]:
df_trkv_trated = tratar_trkv(df_trkv)
df_trkv_trated

In [ ]:

df_trkv['timestr'] = pd.to_datetime(
    df_trkv['timestr'], format='mixed', dayfirst=True, errors='coerce'
)
df_trkv['Data'] = df_trkv['timestr'].dt.date

# Colunas de impacto
colunas_impacto = ['A#L_1', 'A#L_2', 'A#R_1',
                    'A#R_2', 'B#L_1', 'B#L_2', 'B#R_1']

# Substituir valores 0 por NaN
df_trkv[colunas_impacto] = df_trkv[colunas_impacto].replace(
    0, np.nan)

# Calcular o maior valor por linha
df_trkv['Maior_Impacto_Linha'] = df_trkv[colunas_impacto].max(
    axis=1, skipna=True)

# Agrupar por data
df_trkv_max = (
    df_trkv.groupby('Data', as_index=False)['Maior_Impacto_Linha']
    .max()
    .rename(columns={'Maior_Impacto_Linha': 'Maior_Impacto_Diario'})
    .sort_values(by='Data', ascending=True)
)

# Formatar
df_trkv_max['TRKV_MAX_Cunha'] = df_trkv_max['Maior_Impacto_Diario'].round(
    2)
# df_trkv_max = tratar_outliers(df_trkv_max)
# print("-------------------------------------------------------df_trkv_max.head()")
# print(df_trkv_max.head())


df_trkv_max