In [2]:
import numpy as np
import plotly.express as px
import pandas as pd
from datetime import datetime
import re
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
import time
import streamlit as st
from pymongo import MongoClient
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

In [3]:
# functions Begin --------------------------------------------------
# main def
def busca_dados(vagao):
    def busca_z1568(vagao):
        # Conexão com o MongoDB
        vagao = int(vagao)
        client = MongoClient(
            'mongodb+srv://int_dados:e7bUe2bXbKDu3Xzr@rumo-dev2.hbdcrld.mongodb.net/?authSource=admin')

        # Definição do filtro
        filter = {'ATIVO': re.compile(f"{vagao}")}

        # Consulta
        cursor = client['supervisorio']['z1568_Liberacoes_Retencoes_full'].find(
            filter)

        # Converter o cursor em lista e depois em DataFrame
        df = pd.DataFrame(list(cursor))

        # (Opcional) Remover a coluna _id, se não for necessária
        if '_id' in df.columns:
            df.drop('_id', axis=1, inplace=True)

        return df

    def busca_z851(vagao):
        # Conexão com o MongoDB
        vagao = int(vagao)
        client = MongoClient(
            'mongodb+srv://int_dados:e7bUe2bXbKDu3Xzr@rumo-dev2.hbdcrld.mongodb.net/?authSource=admin')

        # Definição do filtro
        filter = {'EQUNR': re.compile(f"{vagao}")}

        # Consulta
        cursor = client['supervisorio']['CadastroVagoes_full'].find(filter)

        # Converter o cursor em lista e depois em DataFrame
        df = pd.DataFrame(list(cursor))

        # (Opcional) Remover a coluna _id, se não for necessária
        if '_id' in df.columns:
            df.drop('_id', axis=1, inplace=True)

        return df

    def busca_wcm(vagao):
        # Conexão com o MongoDB
        client = MongoClient(
            'mongodb+srv://int_dados:e7bUe2bXbKDu3Xzr@rumo-dev2.hbdcrld.mongodb.net/?authSource=admin')
        vagao_str = str(vagao)
        # Pipeline de agregação
        pipeline = [
            {
                '$match': {
                    'json_documents.json_Identificação do veículo': {
                        '$regex': vagao_str,
                        '$options': 'i'
                    }
                }
            },
            {
                '$project': {
                    'json_documents': 1,
                    '_id': 0
                }
            },
            {
                '$unwind': '$json_documents'
            },
            {
                '$match': {
                    'json_documents.json_Identificação do veículo': {
                        '$regex': vagao_str,
                        '$options': 'i'
                    }
                }
            }
        ]

        # Executa a agregação
        result = client['supervisorio']['WCM'].aggregate(pipeline)

        # Converte o resultado em DataFrame
        df = pd.DataFrame(list(result))

        # Se quiser expandir o dicionário 'json_documents' em colunas separadas:
        if not df.empty and 'json_documents' in df.columns:
            df = pd.json_normalize(df['json_documents'])

        return df

    def busca_z369(vagao):
        # Conexão com o MongoDB
        client = MongoClient(
            'mongodb+srv://int_dados:e7bUe2bXbKDu3Xzr@rumo-dev2.hbdcrld.mongodb.net/?authSource=admin')

        vagao_str = str(vagao)

        # Definição do filtro
        filter = {"ATIVO_tratado": vagao_str}

        # Consulta
        cursor = client['supervisorio']['z369_trated'].find(filter)

        # Converter o cursor em lista e depois em DataFrame
        df = pd.DataFrame(list(cursor))

        # (Opcional) Remover a coluna _id, se não for necessária
        if '_id' in df.columns:
            df.drop('_id', axis=1, inplace=True)

        return df

    def busca_TRKV(vagao):
        # Conexão com o MongoDB
        vagao = int(vagao)
        client = MongoClient(
            'mongodb+srv://int_dados:e7bUe2bXbKDu3Xzr@rumo-dev2.hbdcrld.mongodb.net/?authSource=admin')

        # Definição do filtro
        filter = {'CarIDNumber': vagao}

        # Consulta
        cursor = client['supervisorio']['TRKV_treated'].find(filter)

        # Converter o cursor em lista e depois em DataFrame
        df = pd.DataFrame(list(cursor))

        # (Opcional) Remover a coluna _id, se não for necessária
        if '_id' in df.columns:
            df.drop('_id', axis=1, inplace=True)

        return df

    def medir_tempo(func, *args, **kwargs):
        inicio = time.time()
        resultado = func(*args, **kwargs)
        fim = time.time()
        print(f"{func.__name__} executou em {fim - inicio:.2f} segundos")
        return resultado

    def exec_parallel(vagao):
        funcoes = [
            busca_wcm,
            busca_z369,
            busca_TRKV,
            busca_z851,
            busca_z1568
        ]

        resultados = {}

        with ThreadPoolExecutor(max_workers=5) as executor:
            futures = {
                executor.submit(medir_tempo, f, vagao): f.__name__
                for f in funcoes
            }

            for future in as_completed(futures):
                nome = futures[future]
                try:
                    resultados[nome] = future.result()
                except Exception as e:
                    print(f"Erro na função {nome}: {e}")
                    resultados[nome] = None

        return resultados

    result = exec_parallel(vagao)

    df_WCM = result["busca_wcm"]
    df_z369 = result["busca_z369"]
    df_trkv = result["busca_TRKV"]
    df_z851 = result["busca_z851"]
    df_z1568 = result["busca_z1568"]

    print(len(df_WCM))
    print(len(df_z369))
    print(len(df_trkv))
    print(len(df_z851))
    print(len(df_z1568))
    st.success("Função executada com sucesso!")

    return df_WCM, df_z369, df_trkv, df_z851, df_z1568

def tratar_dfs(df_WCM, df_z369, df_trkv):

    def tratar_trkv(df_trkv):
        # Converter datas (aceita ISO e dd/mm/yyyy)
        df_trkv['timestr'] = pd.to_datetime(
            df_trkv['timestr'], format='mixed', dayfirst=True, errors='coerce'
        )
        df_trkv['Data'] = df_trkv['timestr'].dt.date

        # Colunas de impacto
        colunas_impacto = ['A#L_1', 'A#L_2', 'A#R_1',
                            'A#R_2', 'B#L_1', 'B#L_2', 'B#R_1']

        # Substituir valores 0 por NaN
        df_trkv[colunas_impacto] = df_trkv[colunas_impacto].replace(
            0, np.nan)

        # Calcular o maior valor por linha
        df_trkv['Maior_Impacto_Linha'] = df_trkv[colunas_impacto].max(
            axis=1, skipna=True)

        # Agrupar por data
        df_trkv_max = (
            df_trkv.groupby('Data', as_index=False)['Maior_Impacto_Linha']
            .max()
            .rename(columns={'Maior_Impacto_Linha': 'Maior_Impacto_Diario'})
            .sort_values(by='Data', ascending=True)
        )

        # Formatar
        df_trkv_max['TRKV_MAX_Cunha'] = df_trkv_max['Maior_Impacto_Diario'].round(
            2)

        return df_trkv_max[['Data', 'TRKV_MAX_Cunha']]

    df_trkv_trated = tratar_trkv(df_trkv)

    def tratar_WCM(df_WCM):
        # Garantir que o campo de tempo esteja em formato datetime
        df_WCM['json_trem_TrainTime'] = pd.to_datetime(
            df_WCM['json_trem_TrainTime'])

        # Criar uma coluna apenas com a data (sem hora)
        df_WCM['Data'] = df_WCM['json_trem_TrainTime'].dt.date

        # Agrupar por dia e pegar o maior valor da força de impacto
        df_WCM_max = (
            df_WCM.groupby('Data', as_index=False)[
                'json_Força de pico de impacto da roda (kN)']
            .max()
            .rename(columns={'json_Força de pico de impacto da roda (kN)': 'Maior_Impacto_kN'})
            # ✅ organiza do mais antigo para o mais recente
            .sort_values(by='Data', ascending=True)
        )
        return df_WCM_max
    df_wcm_trated = tratar_WCM(df_WCM)

    def tratar_z369(df_z369):

        # df_z369['timestr'] = pd.to_datetime(df_z369['timestr'])
        # df_z369['Data'] = df_z369['timestr'].dt.date

        df_z369['Texto_Completo'] = (
            df_z369[['TEXTO', 'TEXTO AVARIA', 'TEXTO CAUSA']]
            .fillna('')  # substitui NaN por vazio
            .agg(' | '.join, axis=1)  # concatena linha a linha
            .str.strip(' | ')  # remove separador no fim se faltar campo
        )

        df_z369_trated = df_z369[['NOTA', 'ATIVO', 'TP NOTA', 'STATUS',
                                    'dt_abertura_trated', 'dt_fechamento_trated', 'Texto_Completo']]

        df_z369_Aberturas = df_z369_trated[[
            'dt_abertura_trated', 'TP NOTA', 'NOTA', 'Texto_Completo', 'STATUS']]
        df_z369_Aberturas["Evento"] = "Abertura"
        df_z369_Aberturas = df_z369_Aberturas.rename(columns={
            'dt_abertura_trated': 'Data',
        })

        df_z369_fechamentos = df_z369_trated[df_z369_trated['dt_fechamento_trated'].notnull(
        )]
        df_z369_fechamentos = df_z369_fechamentos[[
            'dt_fechamento_trated', 'TP NOTA', 'NOTA', 'Texto_Completo', 'STATUS']]
        df_z369_fechamentos = df_z369_fechamentos.rename(columns={
            'dt_fechamento_trated': 'Data',
        })
        df_z369_fechamentos["Evento"] = "Fechamento"

        # Concatenar os dois dataframes um embaixo do outro
        df_z369_total = pd.concat(
            [df_z369_Aberturas, df_z369_fechamentos], ignore_index=True)

        # Ordenar pela coluna "Data"
        df_z369_total = df_z369_total.sort_values(
            by='Data', ascending=True).reset_index(drop=True)
        df_z369_total["NOTA"] = "NOTA-" + df_z369_total["NOTA"].astype(str)

        return df_z369_total, df_z369_trated

    df_z369_total, df_z369_trated = tratar_z369(df_z369)

    return df_trkv_trated, df_wcm_trated, df_z369_total, df_z369_trated

def inserir_wcm_hist(df_wcm_trated):
    df_wcm_trated_histgeral = df_wcm_trated.copy()
    # 1) Garantir datetime (com hora) na coluna Data
    df_wcm_trated_histgeral['Data'] = pd.to_datetime(
        df_wcm_trated_histgeral['Data'])
    df_wcm_trated_histgeral['TP NOTA'] = "Passagem wcm"
    df_wcm_trated_histgeral['NOTA'] = "wcm_" + \
        df_wcm_trated_histgeral['Data'].astype(str)
    df_wcm_trated_histgeral['Texto_Completo'] = "Maior_Impacto_kN = " + \
        df_wcm_trated_histgeral['Maior_Impacto_kN'].astype(str)

    df_wcm_trated_ab = df_wcm_trated_histgeral.copy()
    df_wcm_trated_ab['Evento'] = "Abertura"

    df_wcm_trated_fx = df_wcm_trated_histgeral.copy()
    df_wcm_trated_fx['Data'] = df_wcm_trated_fx['Data'] + \
        pd.to_timedelta(12, unit='h')
    df_wcm_trated_fx['Evento'] = "Fechamento"

    # Agora sim, cada um é independente
    df_wcm_total = pd.concat(
        [df_wcm_trated_ab, df_wcm_trated_fx], ignore_index=True)
    df_wcm_total = df_wcm_total[[
        'Data', 'TP NOTA', 'NOTA', 'Texto_Completo', 'Evento']]

    return df_wcm_total

def inserir_trkv_hist(df_trkv_trated):
    df_trkv_trated_histgeral = df_trkv_trated.copy()
    df_trkv_trated_histgeral['Data'] = pd.to_datetime(
        df_trkv_trated_histgeral['Data'])
    df_trkv_trated_histgeral['TP NOTA'] = "Passagem trkv"
    df_trkv_trated_histgeral['NOTA'] = "trkv_" + \
        df_trkv_trated_histgeral['Data'].astype(str)
    df_trkv_trated_histgeral['Texto_Completo'] = "TRKV_MAX_Cunha = " + \
        df_trkv_trated_histgeral['TRKV_MAX_Cunha'].astype(str)

    df_trkv_trated_ab = df_trkv_trated_histgeral.copy()
    df_trkv_trated_ab['Evento'] = "Abertura"

    df_trkv_trated_fx = df_trkv_trated_histgeral.copy()
    df_trkv_trated_fx['Data'] = df_trkv_trated_fx['Data'] + \
        pd.to_timedelta(12, unit='h')
    df_trkv_trated_fx['Evento'] = "Fechamento"

    # Agora sim, cada um é independente
    df_trkv_total = pd.concat(
        [df_trkv_trated_ab, df_trkv_trated_fx], ignore_index=True)
    df_trkv_total = df_trkv_total[[
        'Data', 'TP NOTA', 'NOTA', 'Texto_Completo', 'Evento']]

    return df_trkv_total

In [11]:
vg_entrada = "336700"
df_WCM, df_z369, df_trkv, df_z851, df_z1568 = busca_dados(vg_entrada)

c:\Users\leona\anaconda3\Lib\site-packages\pymongo\pyopenssl_context.py:352: CryptographyDeprecationWarning: Parsed a negative serial number, which is disallowed by RFC 5280. Loading this certificate will cause an exception in the next release of cryptography.
  _crypto.X509.from_cryptography(x509.load_der_x509_certificate(cert))

busca_z1568 executou em 7.91 segundos
busca_z851 executou em 7.96 segundos
busca_TRKV executou em 8.05 segundos
busca_z369 executou em 8.54 segundos
busca_wcm executou em 9.44 segundos
48
11
8
1
2

In [12]:
df_trkv

,CarSequenceNumber,CarIDInitial,CarIDNumber,CarOrientation,CarType,TruckFields,TruckIDs,TruckValues,timestr,Header_TrainSequenceNumber_int,A#L_1,A#L_2,A#R_1,A#R_2,B#L_1,B#L_2,B#R_1,B#R_2,data_sincronizacao,concatenatedCarID
0,49,HPT,336700.0,A,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#A#L#4#2#N*Truck#A#R#4#2#F*Truck#B#L#2#1#...,0###0.841#0.841#0#0######2#####*0###0.654#1.02...,01/10/2025 08:24:11,39540,21.3614,21.3614,16.6116,26.1112,20.8788,25.1460,20.8788,23.7236,2025-11-13 12:01:58.518,0336700HPT
1,97,HPT,336700.0,A,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#A#R#4#2#N*Truck#A#L#4#2#F*Truck#B#R#2#1#...,0###0.673#1.065#0#0######2#####*0###1.028#0.99...,06/10/2025 20:15:55,39725,26.1112,25.1460,17.0942,27.0510,27.0510,28.0162,23.2664,23.7236,2025-11-13 12:01:58.518,0336700HPT
2,76,HPT,336700.0,B,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#B#R#1#1#N*Truck#B#L#1#1#F*Truck#A#R#3#2#...,0#####0#0######2#####*2#################*2####...,10/10/2025 03:18:52,39846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-11-13 12:01:58.518,0336700HPT
3,35,HPT,336700.0,A,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#A#L#4#2#N*Truck#A#R#4#2#F*Truck#B#L#2#1#...,0###1.028#0.878#0#0######2#####*0###0.841#1.12...,19/10/2025 15:13:26,40220,26.1112,22.3012,21.3614,28.4734,26.1112,NaN,26.5938,25.1460,2025-11-13 12:01:58.518,0336700HPT
4,106,HPT,336700.0,A,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#A#L#4#2#N*Truck#A#R#4#2#F*Truck#B#L#2#1#...,0###0.822#0.804#0#0######2#####*0###0.729#0.89...,06/09/2025 13:35:24,38764,20.8788,20.4216,18.5166,22.7838,19.4564,25.6286,20.4216,22.3012,2025-11-13 12:01:58.518,0336700HPT
5,66,HPT,336700.0,A,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#A#L#4#2#N*Truck#A#R#4#2#F*Truck#B#L#2#1#...,0###0.822#0.822#0#0######2#####*0###0.710#0.97...,15/09/2025 08:01:39,39048,20.8788,20.8788,18.0340,24.6888,19.4564,25.1460,19.9390,23.7236,2025-11-13 12:01:58.518,0336700HPT
6,126,HPT,336700.0,B,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#B#L#1#1#N*Truck#B#R#1#1#F*Truck#A#L#3#2#...,0###1.009#1.009#0#0######2#####*0###0.990#0.99...,27/09/2025 06:37:34,39404,25.6286,21.8440,20.4216,28.0162,25.6286,25.6286,25.1460,25.1460,2025-11-13 12:01:58.518,0336700HPT
7,34,HPT,336700.0,B,R,MeasureErrorCode*VTAValveDefect*EarthStrapMiss...,Truck#B#L#1#1#N*Truck#B#R#1#1#F*Truck#A#L#3#2#...,0###1.047#1.028#0#0######2#####*0###1.028#0.99...,04/11/2025 17:38:16,40759,26.5938,21.3614,20.8788,29.4386,26.5938,26.1112,26.1112,25.1460,2025-11-13 12:01:58.518,0336700HPT

In [5]:
def tratar_z369(df_z369):

    # df_z369['timestr'] = pd.to_datetime(df_z369['timestr'])
    # df_z369['Data'] = df_z369['timestr'].dt.date

    df_z369['Texto_Completo'] = (
        df_z369[['TEXTO', 'TEXTO AVARIA', 'TEXTO CAUSA']]
        .fillna('')  # substitui NaN por vazio
        .agg(' | '.join, axis=1)  # concatena linha a linha
        .str.strip(' | ')  # remove separador no fim se faltar campo
    )

    df_z369_trated = df_z369[['NOTA', 'ATIVO', 'TP NOTA', 'STATUS',
                                'dt_abertura_trated', 'dt_fechamento_trated', 'Texto_Completo']]
    
    df_timeline_z369 = df_z369_trated.copy()

    df_timeline_z369 = df_timeline_z369.rename(columns={
            "NOTA": "Evento",
            "TP NOTA": "Tipo_Evento",
            "dt_abertura_trated": "INICIO",
            "dt_fechamento_trated": "FIM"
        })


    return df_timeline_z369, df_z369_trated

df_timeline_z369, df_z369_trated = tratar_z369(df_z369)

In [22]:
df_z1568

,Documento,ATIVO,DATA FIM,DATA INICIO,DATAREC,DISPONIBILIDADE,DT_HR_RET,ESCOPO,GRUPO_AVARIA,HORA FIM,...,RETENCAO,RET_INDEVIDA,SEQUENCIAL,STATUS,TEXTO,VAGAO,data_sincronizacao,dt_fim_trated,dt_inicio_trated,dt_modificacao
0,1689231,0336700HPT,20240607,20240415,20240415,DISPONIVEL,20240415045201,MC,TRUQUE,224856,...,DISPONIVEL,NÃO,0000000000,EM TRAB.,ZRO:(MC PMV)CAB A E B ANEL DO PRATO AVARIADO +...,0336700,2025-11-12 18:08:30.712,2024-06-07,2024-04-15,2024-06-07 22:49:06
1,1761739,0336700HPT,20250826,20250814,20250810,DISPONIVEL,20250814134600,RA,REVISÃO,231048,...,DISPONIVEL,NÃO,0000178476,EM TRAB.,ZRO:(MP T9)REVISÃO RA +|3E RIDE CONTROL+INSPEÇ...,0336700,2025-11-12 18:08:30.712,2025-08-26,2025-08-14,2025-08-26 23:10:53

In [ ]:
def inserir_z1568(df_z1568):

    # df_z1568['timestr'] = pd.to_datetime(df_z1568['timestr'])
    # df_z1568['Data'] = df_z1568['timestr'].dt.date

    df_z1568['Texto_Completo'] = (
        df_z1568[['PMV', 'STATUS', 'GRUPO_AVARIA', 'TEXTO']]
        .fillna('')  # substitui NaN por vazio
        .agg(' | '.join, axis=1)  # concatena linha a linha
        .str.strip(' | ')  # remove separador no fim se faltar campo
    )

    df_z1568_trated = df_z1568[['Documento', 'ATIVO', 'ID_Manutecao', 'STATUS',
                                'dt_inicio_trated', 'dt_fim_trated', 'Texto_Completo','ID_Manutecao']]
    
    df_timeline_z1568 = df_z1568_trated.copy()

    df_timeline_z1568 = df_timeline_z1568.rename(columns={
            "NOTA": "Evento",
            "ID_Manutecao": "Tipo_Evento",
            "dt_inicio_trated": "INICIO",
            "dt_fim_trated": "FIM"
        })


    return df_timeline_z1568

df_timeline_z1568 = inserir_z1568(df_z1568)

KeyError: "['TP NOTA'] not in index"

In [ ]:
df_trkv_trated

In [ ]:
from pymongo import MongoClient
from datetime import datetime

client = MongoClient("mongodb+srv://int_dados:e7bUe2bXbKDu3Xzr@rumo-dev2.hbdcrld.mongodb.net/?authSource=admin")
db = client["supervisorio"]
collection = db["base_last_update"]

def update_last_sync(base_name: str):
    """
    Atualiza a data de sincronização de uma base.
    
    Params:
        base_name (str): Nome da base a atualizar.
        
    Efetua upsert: se não existir, cria.
    """
    now = datetime.now()

    result = collection.update_one(
        {"base": base_name},
        {"$set": {"last_update": now}},
        upsert=True
    )

    print(f"✔ Atualizado: {base_name} → {now}")
    return result

def inserir_wcm_hist(df_wcm_trated):
    df_wcm_trated_histgeral = df_wcm_trated.copy()
    print(df_wcm_trated)
    # 1) Garantir datetime (com hora) na coluna Data
    df_wcm_trated_histgeral['INICIO'] = pd.to_datetime(
        df_wcm_trated_histgeral['Data'])
    df_wcm_trated_histgeral['Tipo_Evento'] = "Passagem wcm"
    # + \            df_wcm_trated_histgeral['Data'].astype(str)
    df_wcm_trated_histgeral['Evento'] = "wcm"

    df_wcm_trated_histgeral['Texto_Completo'] = "Maior_Impacto_kN = " + \
        df_wcm_trated_histgeral['Maior_Impacto_kN'].astype(str)

    df_wcm_trated_histgeral["Data"] = pd.to_datetime(
        df_wcm_trated_histgeral["Data"], format="%Y-%m-%d %H:%M")
    df_wcm_trated_histgeral["FIM"] = (
        df_wcm_trated_histgeral["Data"] + pd.to_timedelta(12, unit="h")
    )
    df_wcm_trated_histgeral['Tipo_Evento'] = "WCM"

    df_wcm_total = df_wcm_trated_histgeral[[
        'Evento', 'INICIO', 'FIM', 'Texto_Completo', 'Tipo_Evento']]

    return df_wcm_total